HTML-712: <drugOrder/> tag to be supported on  platform 2.*
openmrs/openmrs-module-htmlformentry pull request #174
Opened 2020-04-16 09:04 UTC by Ruhanga

Ticket: https://issues.openmrs.org/browse/HTML-712

2020-04-16 10:23 UTC, mks-d commented on api-1.10/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement1_10.java
> +		drugOrder.setDateActivated(session.getEncounter().getEncounterDatetime());
@mogoodrich beyond 1.10.x this does not work in ENTER mode because the drug order's date activated must be:
1. On or after the encounter datetime.
2. Before `Date.now()` (not a future datetime.)

... the only possible option in ENTER mode is to set it to be exactly the encounter date time. This is actually what's done in OE OWA.

2020-04-16 10:25 UTC, mks-d commented on api-2.0/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement2_0.java
> +}
Ideally in ENTER mode we want the submission element to remove the start date widget since it cannot be used.

2020-04-16 14:31 UTC, mogoodrich commented on api-1.10/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement1_10.java
> +		drugOrder.setDateActivated(session.getEncounter().getEncounterDatetime());
Technically if you were retrospectively entered an encounter in ENTER mode you could set the order date differently than the encounter date as long as it was after the encounter date and before now, correct?

  (That being said, I'm fine with just making it be the encounter date, as that is probably the 98% use case)

2020-04-16 14:34 UTC, mogoodrich commented on api-2.0/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement2_0.java
> +}
Yeah, if I'm understanding everything that makes sense to me... I haven't seen a screen shot of this widget in some time.

Also, you can't edit a date activated as far as I know, so what would you be doing in EDIT mode?  You could add a new order to the encounter, I guess, but wouldn't that still fall under the same restrictions as ENTER mode?

2020-04-16 14:37 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement.java
> +	    				startDateWidget.setInitialValue(getDrugOrderStartDate(drugOrder));
So you are allowed to edit the start date of existing order?  Does this work?  (Seems like you are just modifying existing code, so I guess it does?)

2020-09-21 14:51 UTC, mseaton requested changes
@Ruhanga and @mks-d - sorry for the late review on this.  I need to add this support in myself and was reminded of this PR.  Not sure what your current cycles are for working on this.  How do you feel about me merging this into a shared branch and collaborating with you on it?

2020-09-21 14:51 UTC, mseaton commented on api-1.10/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement1_10.java
> +		drugOrder.setDateActivated(session.getEncounter().getEncounterDatetime());
@Ruhanga / @mks-d - I agree that we should always set dateActivated to the encounterDatetime in ENTER mode.  And I think this should be true whether entering a retrospective encounter or not (eg. the order should always be activated in that encounter).  

The one use case where I think we would still want to support accepting a custom orderTag.startDate would be if it is after the encounterDatetime, in which case it should serve to set the "scheduledDate" property on the drug order, and should cause us to set the order urgency to "ON_SCHEDULED_DATE".

This allows us to retain support for "future orders", which is lost here.

2020-09-21 14:51 UTC, mseaton commented on api-2.0/pom.xml
> +		</dependency>
This needs to be removed.  Nothing in an api jar can contain a dependency on a web artifact.

2020-09-21 14:51 UTC, mseaton commented on api-2.0/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement2_0.java
> +		return dod.getDateActivated();
We should use "dod.getEffectiveStartDate() here, as this will return the scheduledDate if set, otherwise the dateActivated.

2020-09-21 14:51 UTC, mseaton commented on api-2.0/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement2_0.java
> +		orderTag.dose = orderTag.drug.getMinimumDailyDose();
I think for 2.x, we just leave this as an empty implementation and don't do anything here.  It is not apparent to me that "minimumDailyDose" is the what we should be using as a default value for the dose of a given drug.

2020-09-21 14:51 UTC, mseaton commented on api-2.0/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement2_0.java
> +}
Per my comment above, I think we'd keep the startDateWidget, but maybe default it to the encounterDatetime and only allow it to be changed to something on or after that date.

For EDIT mode, I don't think the UI necessarily has to change, but we will need to properly handle this as a REVISE or DISCONTINUE/NEW order.

2020-11-10 16:35 UTC, mseaton commented
This PR is no longer valid given the extensive refactoring in progress with the drugOrder tag

2020-11-10 16:35 UTC, closed without merging