HTML-745: Allow conditions to be pre set with a concept.
openmrs/openmrs-module-htmlformentry pull request #195
Opened 2020-08-14 09:17 UTC by icrc-loliveira

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/HTML-745-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2020-08-17 07:31 UTC, HerbertYiga commented
Thanks for the progress on this,you can also checkout this link to make a better pr https://wiki.openmrs.org/display/docs/Pull+Request+Tips

2020-08-17 16:37 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +			}
Why is this only happening in VIEW mode?

2020-08-17 16:37 UTC, mks-d commented on api/src/test/resources/org/openmrs/module/htmlformentry/include/conditionForm.xml
> +	Preset Condition Without Status: <condition conceptId="e10ffe54-5184-4efe-8960-cd565ec1cdf8" controlId="preset_condition_without_status" />
Why would those two last tags behave differently from each other?

2020-08-17 16:42 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +			// Handle Condition Clinical Status
I don't think we need all those comments ;-)

2020-08-17 16:45 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +		ret.append("<div id=\"" + searchWidgetWrapperId + "\">");
Did you nest elements even more, if so why was this needed?

2020-08-17 16:55 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +			}
This might be the only way but I'm not comfortable with this. `ConditionElement`implements `FormSubmissionControllerAction` and could provide its own validation, see an example [here](https://github.com/openmrs/openmrs-module-htmlformentry/blob/444e0c599fd896fd24ccc71946b35ca24a6ca1f2/api/src/main/java/org/openmrs/module/htmlformentry/element/ImmunizationSubmissionElement.java#L174-L194).

2020-08-18 07:47 UTC, icrc-loliveira commented on api/src/test/resources/org/openmrs/module/htmlformentry/include/conditionForm.xml
> +	Preset Condition Without Status: <condition conceptId="e10ffe54-5184-4efe-8960-cd565ec1cdf8" controlId="preset_condition_without_status" />
The tags are the same but the test is different.
In the second one the condition is not save because it doesn't have a status.

2020-08-18 07:52 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +		ret.append("<div id=\"" + searchWidgetWrapperId + "\">");
This, I did because seems to be easier to understand it in  the `html` page. And  think that will be useful when I have to align then in a row.

2020-08-18 07:55 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +			}
Actually this only happens if **not** in VIEW mode, because in view mode is already not editable.

2020-08-18 08:31 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +			}
But if I do that, it will have to end with an error right? And that not the goal.

2020-08-19 08:24 UTC, mks-d requested changes
I have a suggestion for a more readable `handleSubmission` altogether, see here:
```java
@Override
public void handleSubmission(FormEntrySession session, HttpServletRequest submission) {
    
    FormEntryContext context = session.getContext();
    
    Condition condition = bootstrap(context);
    
    CodedOrFreeText conditionConcept = new CodedOrFreeText();
    try {
        int conceptId = Integer.parseInt((String) conditionSearchWidget.getValue(session.getContext(), submission));
        conditionConcept.setCoded(Context.getConceptService().getConcept(conceptId));
    }
    catch (NumberFormatException e) {
        String nonCodedConcept = submission.getParameter(context.getFieldName(conditionSearchWidget));
        if (StringUtils.isBlank(nonCodedConcept) && !required) {
            // ignore silently
            return;
        }
        conditionConcept.setNonCoded(nonCodedConcept);
    }
    condition.setCondition(conditionConcept);
    
    ConditionClinicalStatus status = getStatus(context, submission);
    condition.setClinicalStatus(status);
    
    condition.setOnsetDate(onSetDateWidget.getValue(context, submission));
    if (status != ConditionClinicalStatus.ACTIVE) {
        condition.setEndDate(endDateWidget.getValue(context, submission));
    }
    
    condition.setPatient(session.getPatient());
    
    condition.setFormField(FORM_NAMESPACE, session.generateControlFormPath(controlId, 0));
    
    if (concept != null && status == null && !required) {
        return;
    }
    
    session.getEncounter().addCondition(condition);
}
```
Could you try it?
I stopped handling the VIEW mode, I think it was never necessary but please confirm. HFE should not even attempt to handle submission in VIEW mode at all.

I preferred to return early, that is more in the spirit of the submission handling:
```java
if (concept != null && status == null && !required) {
  return;
}
```
For the sake of completeness I took "required" into account. And I think it will connect to my last remark below.

Note that [this](https://github.com/openmrs/openmrs-module-htmlformentry/blob/c24493e811f77a5cc4993e01761e11c3c827a447/api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java#L76-L79) preexisting bit of code seems wrong to me:
```java
if (StringUtils.isBlank(nonCodedConcept) && !required) {
  // ignore silently
  return;
}
```
Can you check whether we can get rid of it?

2020-08-19 08:24 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +import java.util.*;
Avoid wildcard imports.

2020-08-19 08:24 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +	private Locale locale = Context.getLocale();
Apparently this variable is not used.

2020-08-20 08:51 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +import java.util.*;
done.

2020-08-20 08:51 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +	private Locale locale = Context.getLocale();
Removed.

2020-08-20 09:56 UTC, mks-d requested changes

2020-08-20 09:56 UTC, mks-d commented on api/src/test/resources/org/openmrs/module/htmlformentry/include/conditionForm.xml
>  </htmlform>
I would change this test form resource to be this:
```html
<htmlform>

    Date: <encounterDate/>
    Location: <encounterLocation/>
    Provider: <encounterProvider role="Provider"/>

    Required Coded Condition: <condition required="true" controlId="required_coded_condition" />
    Required Non-coded Condition: <condition required="true" controlId="required_noncoded_condition" />
    Preset Condition: <condition conceptId="e10ffe54-5184-4efe-8960-cd565ec1cdf8" controlId="optional_preset_condition" />
</htmlform>
```
And I would adapt the test(s) accordingly.

In that case you could revert to having only one test case where it is made clear that
1. The first tag is used to test creation (ENTER) and edition (EDIT) for a **required coded condition**.
1. The second tag is used to test creation (ENTER) and edition (EDIT) for a **required non-coded (free text) condition**.
1. The third tag is used to test creation (ENTER) and edition (EDIT) for a **non-required preset coded condition**.

2020-09-07 10:40 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				request.addParameter(searchWidgetIdForRequiredNonCodedCondition, "Some required Non-coded Condition");
Give it a real name like `"Anemia (non-coded)"`.

2020-09-07 10:40 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				Assert.assertEquals("Some preset condition", presetCondition.getCondition().getNonCoded());
We see [here](https://github.com/openmrs/openmrs-module-htmlformentry/pull/195/files#diff-8114c8fc23ce7adba0d8a86549f8e829R9) that the preset condition is the concept with UUID `"e10ffe54-5184-4efe-8960-cd565ec1cdf8"`. Something goes wrong if in the end you can assert that what is submitted is non-coded.

2020-09-07 10:40 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				request.addParameter(searchWidgetIdForPresetCondition, "Some preset condition");
Same here, whatever, `"Glaucoma (coded)"`.

2020-09-07 10:40 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
> +		if (presetConcept != null && status == null && !required) {
You can actually add a comment above that line:
```java
// a non-required preset concept will not be submitted
```

2020-09-07 11:25 UTC, icrc-loliveira commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				Assert.assertEquals("Some preset condition", presetCondition.getCondition().getNonCoded());
The widget should not allow you to select a non-code condition.

2020-09-07 14:56 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				Assert.assertEquals("Anemia (non-coded)", pastCondition.getCondition().getNonCoded());
Using the preset concept attribute means that the condition will be _coded_. How can you end up asserting a non-coded condition then?

2020-09-07 14:56 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionElementTest.java
> +	public void handleSubmission_shouldNotSaveIfConceptTagDefinedAndNoStatus() {
→ `handleSubmission_shouldNotSubmitTagWithPresetConceptAndWithoutStatus`

2020-09-07 15:29 UTC, icrc-loliveira commented on api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
> +				Assert.assertEquals("Anemia (non-coded)", pastCondition.getCondition().getNonCoded());
This assert is for a non-coded condition. the `Glaucoma (coded)` is the one that test the preset condition.

2020-09-09 08:11 UTC, mks-d requested changes

2020-09-09 08:11 UTC, mks-d commented on api/src/test/resources/org/openmrs/module/htmlformentry/include/conditionForm.xml
>  </htmlform>
@icrc-loliveira can expand test cases to all possibilities at this point:
```xml
<htmlform>

    Date: <encounterDate/>
    Location: <encounterLocation/>
    Provider: <encounterProvider role="Provider"/>

    Optional Coded Condition: <condition required="false" controlId="optional_coded_condition" />
    Required Coded Condition: <condition required="true" controlId="required_coded_condition" />
    Optional Non-coded Condition: <condition required="false" controlId="optional_noncoded_condition" />
    Required Non-coded Condition: <condition required="true" controlId="required_noncoded_condition" />
    Preset Condition: <condition conceptId="e10ffe54-5184-4efe-8960-cd565ec1cdf8" controlId="optional_preset_condition" />
</htmlform>
```
(I assume that preset ones are always optional.)

2020-09-16 19:51 UTC, mks-d reviewed
@icrc-loliveira it would be interesting to build better test scenarios.
For instance show that it's fine to create the encounter (ENTER mode) with missing inputs for optional tags, but then that it is ok to enrich the encounter (EDIT mode) with those tags.
Or for example that it is ok to remove conditions form the encounter.

The tests here just show that every tag gets submitted in ENTER mode, optional or not.

2020-09-29 13:01 UTC, mks-d reviewed
@icrc-loliveira just a last doubt, when the tag is used with a preset concept (so when the `"conceptId"` attribute is being used), it can't be changed within the form anymore right? In other words, that part of the tag becomes read-only?

2020-09-29 13:17 UTC, icrc-loliveira commented
Yes, The search box stays with the defined concept set as default, and it becomes read-only.

2020-09-29 16:03 UTC, mks-d approved these changes

2020-09-29 16:03 UTC, merged