Html 747: Add support to additional detail in conditions
openmrs/openmrs-module-htmlformentry pull request #197
Opened 2020-08-17 10:01 UTC by icrc-loliveira

## Issue I worked on

see https://issues.openmrs.org/browse/HTML-747

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2020-10-02 16:42 UTC, mks-d reviewed
@icrc-loliveira based on the answers given [here](https://talk.openmrs.org/t/condition-entity-naming-plural-or-singular/30418?u=mksd) we will decide whether
1. We should correct the naming (at least within HFE for now) to be "additional details".
2. We should persist and be consistent with Core's naming of "additional detail".

2020-10-05 16:45 UTC, mks-d requested changes
@icrc-loliveira so, you will need to refactor your code to refer to additional detail (singular, "detail" not "details").

Also let's kill HTML-746 through this PR as well, so we're done.

2020-11-23 09:21 UTC, mks-d requested changes
Some quick changes so I can keep reviewing.

2020-11-23 09:21 UTC, mks-d commented on pom.xml
> +        <openMRSVersion>2.3.3-SNAPSHOT</openMRSVersion>
You need to undo this.

2020-11-23 09:21 UTC, mks-d commented on api/src/main/resources/messages_ar.properties
> +#htmlformentry.conditionui.additionalDetail.label=Additional Detail
Please untouch all **messages...properties** except the default one.

2020-11-23 09:44 UTC, mks-d requested changes

2020-11-23 09:44 UTC, mks-d commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/RegressionTest.java
>  				return "simplestFormWithoutProvider";
I guess you edited the wrong file?

2020-11-23 09:44 UTC, mks-d commented on api/src/main/resources/messages_ar.properties
> +#htmlformentry.conditionui.additionalDetail.label=Additional Detail
Please untouch also this one.

2020-11-23 10:48 UTC, icrc-loliveira commented on pom.xml
> +        <openMRSVersion>2.3.3-SNAPSHOT</openMRSVersion>
done

2020-11-23 10:48 UTC, icrc-loliveira commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/RegressionTest.java
>  				return "simplestFormWithoutProvider";
Fix

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandler.java
> +		// Fill show additional detail attribute
You can remove that comment line, the code is obvious.

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
> +		}
Maybe the HTML for recording additional detail could always be generated but hidden when `showAdditionalDetail` is `false`. This would be more in line with the attribute meaning of _show_ additional detail (and would make the test code base easier).

So the signature would become something like:
```java
private String htmlForAdditionalDetailWidget(FormEntryContext context, Boolean visible) {
```
and you'd append HTML like this:
```java
ret.append(htmlForAdditionalDetailWidget(context, showAdditionalDetail));
```

@mogoodrich @mseaton any thoughts on this? Is there any major downside in having a fluffier HTML with hidden `<div/>`s, rather than generating less HTML? What's the typical best practise?

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
> +		ret.append("<div id=\"" + additionalDetailWrapperId + "\">");
So this is where you'd add (or not) `display: none;`.

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
> +		// Create wrapper id
It's all quite obvious, please remove the comments.

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
> +		// Register widget
Same here.

2020-11-24 11:35 UTC, mks-d commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
>  		}
Is the second condition not enough, can you not just do something like:
```java
getAdditionalDetailWidget().setInitialValue(existingCondition != null ? existingCondition.getAdditionalDetail() : null);
```
?

2020-11-24 11:45 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandler.java
> +		// Fill show additional detail attribute
done

2020-11-24 11:46 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
> +		// Create wrapper id
done

2020-11-24 11:48 UTC, icrc-loliveira commented on api-2.3/src/main/java/org/openmrs/module/htmlformentry/element/ConditionElement.java
>  		}
Yes, it should be enough.

2020-11-25 20:28 UTC, mks-d approved these changes

2020-11-25 21:09 UTC, mks-d approved these changes
@mseaton I'm good with this, just asking for a last min final reading.

2020-11-26 09:50 UTC, merged