HTML-761:Obs tag Shows Retired Concept Options with AnswerClasses
openmrs/openmrs-module-htmlformentry pull request #216
Opened 2020-12-01 13:40 UTC by sherrif10

https://issues.openmrs.org/browse/HTML-761
cc @mks-d  @ibacher

2020-12-02 19:40 UTC, ibacher commented on api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
> +							        .getConceptsByClass(cc).stream().filter(it -> !it.getRetired()));
```suggestion
							conceptAnswers.addAll(Context.getConceptService()
							        .getConceptsByClass(cc).stream().filter(it -> !it.getRetired())
							        .collect(Collectors.toList()));
```

2020-12-02 21:11 UTC, sherrif10 commented on api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
> +							        .getConceptsByClass(cc).stream().filter(it -> !it.getRetired()));
Resolved thanks

2020-12-02 21:13 UTC, mogoodrich reviewed
LGTM... but wondering if @mseaton  has any thoughts on this as he recently did a (somewhat) related change to HFE.

2020-12-02 21:16 UTC, sherrif10 commented
Thanks @mogoodrich

2020-12-03 00:18 UTC, mseaton approved these changes
The PR that I'm working on for HTML-765 _should_ ensure that previously saved values will still appear in edit mode, so I don't think this will adversely affect that use case, assuming I get that in.

I'm not 100% sure I agree this fix is needed, but I don't see any harm in it I guess.  One could argue that if a Concept is explicitly added as a valid Answer to a Concept, then it should be displayed, and if you don't want it to be listed any more, just remove it from the allowed answers to a given Question.  @mks-d - looks like you created this ticket, so I'll defer to you on whether you've given that particular thought.

2020-12-03 05:53 UTC, sherrif10 commented
Thanks @mseaton for clarifying, So the idea was that if any concept is retired , it shouldnot reflect again. cc @mks-d

2020-12-03 15:54 UTC, mogoodrich commented
@mseaton  I think this only applies to the "answerClasses" attribute, which displays all concepts that depend to a class or set of classes...

2020-12-03 16:37 UTC, sherrif10 commented
@mogoodrich  Yeah sure basically coded concepts with answerClasses Attribute, so the idea is that Obs tag should not return retired coded concept

2020-12-04 10:02 UTC, sherrif10 commented
Hello @mks-d  Any more suggestion on this work being done here thanks

2020-12-06 06:56 UTC, sherrif10 commented
Shall we have a merge into master because i think its ready cc @mks-d

2020-12-22 06:34 UTC, sherrif10 reviewed
LGTM  this can be merged cc @mksd @dkayiwa  thnks

2021-01-04 10:02 UTC, mks-d requested changes
@mseaton about your comment [here](https://github.com/openmrs/openmrs-module-htmlformentry/pull/216#pullrequestreview-543344284), as @mogoodrich said the scope here is only about the `answerClasses` attribute.

LGTM except for the **.gitignore** file that should be untouched.

2021-01-04 10:21 UTC, sherrif10 commented on api-2.3/.gitignore
> +/target/
ohh sure let me fix it

2021-01-04 11:19 UTC, sherrif10 commented on api-2.3/.gitignore
> +/target/
Resolved thanks

2021-01-04 11:56 UTC, mks-d requested changes

2021-01-04 11:56 UTC, mks-d commented on api-2.3/.gitignore
> +
Still there.

2021-01-04 12:03 UTC, mks-d requested changes

2021-01-04 12:03 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
> +							        .filter(it -> !it.getRetired()).collect(Collectors.toList()));
A last detail, in `it -> !it.getRetired()` just change the variable name from `it` to `c` ("c" for "concept"). More readable.

2021-01-04 17:04 UTC, sherrif10 commented on api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
> +							        .filter(it -> !it.getRetired()).collect(Collectors.toList()));
Thanks @mks-d  have responded to the comment  above

2021-01-04 20:30 UTC, mks-d approved these changes

2021-01-04 20:30 UTC, merged