Html 755 Convert Timezones
openmrs/openmrs-module-htmlformentry pull request #219
Opened 2020-12-15 11:59 UTC by icrc-jfigueiredo

Convert from client Timezone to Server timezone.
Also convert form Server timezone to UTC when sending the date to client.

2021-01-04 21:48 UTC, mks-d requested changes

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +import java.util.*;
Avoid wildcard imports.

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +	private void RegisterDateAndTime(FormEntryContext context, DateWidget widget, Map<String, Object> parameters) {
The naming is most likely wrong (and also method names are always `camelCase`'d in Java).

Is this taking an empty `DateWidget` instance to initialize it from the context and the params?

If yes change the signature to
```java
private void initializeDateWidget(FormEntryContext context, Map<String, Object> parameters, DateWidget widget) {
...
```
With inputs as first args (context and params) and output as last arg (the date widget).

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +	}
What's this method doing exactly? Does it need to be public?

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +			throw new Exception("htmlformentry.error.cannotBeInFuture");
Always embrace `if`s content:
```java
if (date == null) {
  ...
}
```

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +	protected Date initialValue;
This member is already defined [here](https://github.com/openmrs/openmrs-module-htmlformentry/pull/219/files#diff-9a69cc35cad580005d556de11ba79dffaa7873f7b3efaf957a094fb38b61355bR21) in `DateWidget`.

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +	protected boolean hidden;
Same remark.

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				sb.append("<input type=\"hidden\" class=\"hfe-timeZone\" name=\"").append(context.getFieldName(this))
A detail but let's systematically write time zone (in code) as `timezone`, all lower caps.
So this would become `class=\"hfe-timezone\"`.

2021-01-04 21:48 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/DateWidget.java
> +	protected Date initialValue;
You shouldn't need to make all those guys `protected` since you have public getters and setters at the level of `DateWidget`.

2021-01-08 21:13 UTC, mks-d reviewed
I'll make a PR that starts reorganising the code in a way that will make it easier to make `ZonedDateTimeWidget.generateHtml(FormEntryContext)` closer to being build from reused pieces of both `DateWidget` and `TimeWidget`.

For now my main issue is that the VIEW mode turns the datetime into UCT while the EDIT mode doesn't.
That surely isn't ok, what was the thinking there?

2021-01-08 21:13 UTC, mks-d commented on api/src/main/resources/messages.properties
> +htmlformentry.error.handleTimezones=To use timezones the server need to have the variable handleTimezones as true.
This isn't used anywhere is it?

2021-01-08 21:13 UTC, mks-d commented on omod/src/main/resources/config.xml
> +	</globalProperty>
And this isn't used either?

2021-01-11 09:36 UTC, icrc-jfigueiredo commented on api/src/main/resources/messages.properties
> +htmlformentry.error.handleTimezones=To use timezones the server need to have the variable handleTimezones as true.
> I'll make a PR that starts reorganising the code in a way that will make it easier to make `ZonedDateTimeWidget.generateHtml(FormEntryContext)` closer to being build from reused pieces of both `DateWidget` and `TimeWidget`.
> 
> For now my main issue is that the VIEW mode turns the datetime into UCT while the EDIT mode doesn't.
> That surely isn't ok, what was the thinking there?

The Enter/Edit mode get their dates from [HFE-UI](https://github.com/icrc-jfigueiredo/openmrs-module-htmlformentryui/commit/e6f08405d341c057f976546e91728be6c453195a#diff-9920bfbf71a8b9f88051301b5ce589794fa2de063329605ce35381698ee79285) the change to UTC is done there.

2021-01-11 10:11 UTC, icrc-jfigueiredo commented on omod/src/main/resources/config.xml
> +	</globalProperty>
> And this isn't used either?

This is used to set the initial value of the GP to false. In this version i am already using the GP, here and here.
For testing that GP I am setting it to true [here](https://github.com/openmrs/openmrs-module-htmlformentry/pull/219/commits/fa994910c7793ff4562a80bae8574924fc3bbdf6#diff-4fd897c96b3194ac36e52c2765e808d6be3202d2adb2a18780c41fec03b635e0R727) and checking it's value [here](https://github.com/openmrs/openmrs-module-htmlformentry/pull/219/commits/fa994910c7793ff4562a80bae8574924fc3bbdf6#diff-4fd897c96b3194ac36e52c2765e808d6be3202d2adb2a18780c41fec03b635e0R738).

2021-01-15 10:42 UTC, mks-d requested changes

2021-01-15 10:42 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				        .append(getUTCDateFormat().format(initialValue)).append("</span>").toString();
@icrc-jfigueiredo this is problematic, HTML ids should be unique, why couldn't you just do
```java
return WidgetFactory.displayValue(toPrint);
```
as done [here](https://github.com/openmrs/openmrs-module-htmlformentry/blob/a2d606bfb463b70671f4d5c2fadfcf9b77904c85/api/src/main/java/org/openmrs/module/htmlformentry/widget/TimeWidget.java#L51-L54) or [here](https://github.com/openmrs/openmrs-module-htmlformentry/blob/a2d606bfb463b70671f4d5c2fadfcf9b77904c85/api/src/main/java/org/openmrs/module/htmlformentry/widget/DateWidget.java#L80-L83)?

2021-01-15 10:42 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +		// ------------------FOR TESTING TZ-----------------------//
@icrc-jfigueiredo let's go through a cleanup of `EncounterDetailSubmissionElement` now, and in particular that removes the "code for testing" that will not stay.

2021-01-18 10:49 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				        .append(getUTCDateFormat().format(initialValue)).append("</span>").toString();
In this case we use HTML because we want to have a specific ID, so i can see if that ID is present where we execute the client JS, and if that ID is present we convert that date from UTC-> Client TZ.
So we use that html to generate an ID and check if we need to convert that timezone.

2021-01-25 16:36 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +				if (!serverTimezone.equals(clientTimezone) && !handleTimezones && (clientTimezone != null)) {
@icrc-jfigueiredo my thinking here is that `serverTimezone` will never be blank because `TimeZone.getDefault().getID()` should always give _something_.
So if `clientTimezone` is `null`, then this condition is enough: `!serverTimezone.equals(clientTimezone)`.

Am I missing something?

2021-01-25 17:55 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +				if (!serverTimezone.equals(clientTimezone) && !handleTimezones && (clientTimezone != null)) {
You are correct, I was testing some scenarios.

2021-01-25 20:12 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toPrint, "dateTimeWithTimezone");
@icrc-jfigueiredo so this means that the client side code is responsible for turning this RFC 3339 date into what the user is supposed to see (which is indeed one of the the new conventions about time zones and OpenMRS). I guess that happens in HFE UI right?

2021-01-25 21:21 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toPrint, "dateTimeWithTimezone");
Correct, https://github.com/openmrs/openmrs-module-htmlformentryui/compare/master...icrc-jfigueiredo:HTML-755#diff-7543ad74c606f05f56deebe2a2c1eb2ba0cb06eb6de7400957dfe8824939eceeR3

2021-01-25 21:35 UTC, mks-d requested changes

2021-01-25 21:35 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toPrint, "dateTimeWithTimezone");
Let's rename this class `"date-with-timezone"`, ref. https://csswizardry.com/2010/12/css-camel-case-seriously-sucks/

2021-01-29 13:59 UTC, mks-d reviewed
@mogoodrich I have done a walk through set of comments for you...

2021-01-29 13:59 UTC, mks-d commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/RegressionTest.java
> +				request.setParameter("w1timezone", TimeZone.getDefault().getID()); // making sure that client tz = server tz
@mogoodrich actually this is where we see some non-backward compatible stuff. The new behaviour of `<encounterDate showTime="true"/>` implies that a `timezone` parameter must be submitted or an an exception is thrown (exception that didn't exist before).

2021-01-31 19:24 UTC, dkayiwa commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
How about putting them in openmrs core and we back port? Then a module like this could have a comment with instructions to remove this duplicated code once we upgrade to the openmrs core version with these new methods.

2021-02-01 15:31 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
@dkayiwa that's 🎼 to my ears. Makes sense.
I'll need to do a little roundtable with people so that we agree on which methods that should be those Core time zone utils, but otherwise that's the idea.

2021-02-01 22:20 UTC, mogoodrich approved these changes
Had a few comments, but generally looks good to me.

I'm generally happy that this doesn't seem to to touch *too* much of the code yet, though that may change as you apply it to other widgets.

I'll be happy to run this through our smoke tests and do some manual testing once this goes though, thanks!

2021-02-01 22:20 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
> +	public final static String GP_HANDLE_TIMEZONES = "htmlformentry.handleTimezones";
Okay... I will only review the encounter date stuff then, I may have further comments on follow-on commits?

2021-02-01 22:20 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +		return ISODateTimeFormat.dateTime().print(new DateTime(date.getTime(), UTC));
Just to confirm, this is the same format that our REST endpoints use?

2021-02-01 22:20 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
> +					throw new IllegalStateException("htmlformentry.error.handleTimezones");
Makes sense to me!

2021-02-01 22:20 UTC, mogoodrich commented on omod/src/main/resources/config.xml
> +		</description>
This isn't necessarily true, correct?  If you have got an encounterDate with showTime='false' it will still revert to the old behavior even if this GP is set to true?  (

2021-02-02 09:02 UTC, icrc-jfigueiredo commented on omod/src/main/resources/config.xml
> +		</description>
Correct, for now, to be able to use timezones we need to have showTime='true' AND the GP true or the serer timezone be the same as the client timezone.

2021-02-02 22:28 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +		return ISODateTimeFormat.dateTime().print(new DateTime(date.getTime(), UTC));
@mogoodrich yes.

2021-02-02 22:28 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
@dkayiwa @mseaton should we try to match what Core will provide?
Like having such package: `org.openmrs.util.TimeZoneUtil`?

2021-02-02 22:35 UTC, mks-d commented on omod/src/main/resources/config.xml
> +		</description>
@mogoodrich, what about:

>When set to true dates are sent from the server to the client as UTC dates, and time-sensitive widgets send dates from the client to the server as holding the client time zone information.

?

`<encounterDate showTime="false"/>` would be considered as a non time-sensitive widget (whereas `<encounterDate showTime="true"/>` is.)

2021-02-02 22:35 UTC, dkayiwa commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
Looks like that has been the practice for things we intend to eventually move into core. That way, module developers do not have to change the package name.

2021-02-02 22:38 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
Ok. @dkayiwa any existing util class that we should add those methods to in your opinion? Rather than adding yet another util class.

2021-02-02 22:45 UTC, dkayiwa commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	}
Though the `OpenmrsUtil` class already has some date utilities, i find it bloated with too many responsibilities. I therefore find it cleaner to use a new utility class.

2021-02-02 23:09 UTC, mogoodrich commented on omod/src/main/resources/config.xml
> +		</description>
I *think* I get it... :)

2021-02-03 09:47 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toRFC3339(initialValue), "rfc3339-date");
@mogoodrich just bringing your attention to this as well. In VIEW mode dates as rendered as RFC 3339 (as agreed) and we have tagged them with the CSS class `.rfc3339-date` so that there's an easy marker for any client side code to localize them.

2021-02-03 14:51 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toRFC3339(initialValue), "rfc3339-date");
So you are kind of relying on there being some client-side code to render it in a human-readable format?  (that's fine with me, just confirming)

2021-02-03 15:07 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toRFC3339(initialValue), "rfc3339-date");
I will go as far as saying that it's (one of) our new conventions: https://wiki.openmrs.org/display/docs/Time+Zones+Conventions#TimeZonesConventions-ClientDisplay:InLocalTimeZone :)

2021-02-03 15:16 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toRFC3339(initialValue), "rfc3339-date");
The convention just seems sort of weird in this old model (where the server is rendering what was originally assumed to be simple display text, not actual objects)... but, again, I don't see a way around it, so I'm okay with it.

2021-02-03 15:39 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ZonedDateTimeWidget.java
> +				return WidgetFactory.displayValue(toRFC3339(initialValue), "rfc3339-date");
Sure, you mean old school HFE predating UIFR?

As @bmamlin said ([here](https://talk.openmrs.org/t/hfe-better-handling-of-timezones/31659/26?u=mksd)) the convention is a guide to the best practise, not a mandatory rule:

>The goal of conventions is not to make unbreakable rules; rather, to define & promote best (preferred) practice and make it easier to identify when we are breaking our conventions (so we have to justify breaking them).

2021-03-29 08:39 UTC, mks-d requested changes

2021-03-29 08:39 UTC, mks-d commented on omod/src/main/resources/config.xml
> +		<property>uiframework.timezone.conversions</property>
Same here.

2021-03-29 08:39 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
> +	public final static String GP_TIMEZONE_CONVERSIONS = "uiframework.timezone.conversions";
This will have to be
```java
"htmlformentry.timezone.conversions"
```
HFE can be used outside of UIFR and cannot refer to (or take care of creating) a UIFR-specific GP.

However for UIFR-dependent modules, only the UIFR GP will be checked. So in practise `"uiframework.timezone.conversions"` will superseed `"htmlformentry.timezone.conversions"`.

2021-03-29 08:39 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
>  				boolean handleTimezones = Boolean.parseBoolean(
Maybe `handleTimezones` → `convertTimezones`?

2021-03-29 08:52 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
>  				boolean handleTimezones = Boolean.parseBoolean(
Sure.

2021-03-29 08:56 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
>  				boolean handleTimezones = Boolean.parseBoolean(
But in that case, maybe we should also change [this ](https://github.com/openmrs/openmrs-module-uiframework/compare/master...icrc-jfigueiredo:HTML-755-2#diff-6e177127ee5b17a0d0a088acefa4c4d980d03a506959223081b579f153e8382fR629)on UiFramework UiUtils.

2021-04-08 10:05 UTC, mks-d approved these changes

2021-04-08 13:16 UTC, mogoodrich commented
I know I approved this a few months ago, I see @mks-d  just approved it... any changes I should re-review?

2021-04-08 20:06 UTC, icrc-jfigueiredo commented
Hi @mogoodrich the last changes we made, were mostly about changing names. But please feel free to review it. Thank you

2021-04-15 15:09 UTC, icrc-jfigueiredo commented
Hi @mogoodrich , what do you think about removing [this ](https://github.com/icrc-jfigueiredo/openmrs-module-htmlformentry/blob/HTML-755/api/src/main/java/org/openmrs/module/htmlformentry/widget/TimeWidget.java#L164) condition:
`if (h == 0 && m == 0 && s == 0) {
				return null;
			}` , this is in TimeWidget, with this condition it is not possible to save a form at midnight (00:00:00).

2021-04-15 17:42 UTC, mogoodrich commented
> Hi @mogoodrich , what do you think about removing [this ](https://github.com/icrc-jfigueiredo/openmrs-module-htmlformentry/blob/HTML-755/api/src/main/java/org/openmrs/module/htmlformentry/widget/TimeWidget.java#L164) condition:
> `if (h == 0 && m == 0 && s == 0) { return null; }` , this is in TimeWidget, with this condition it is not possible to save a form at midnight (00:00:00).
> CC:@mks-d

Seem fine/correct to me!

2021-04-20 10:39 UTC, dkayiwa commented on api/src/main/resources/messages.properties
> +htmlformentry.chooseAnEncounterRole                     = Choose an Encounter Role
Did you add these spaces by accident?

2021-04-20 10:39 UTC, dkayiwa commented on api/src/main/resources/messages.properties
> +htmlformentry.conditionui.onsetdate.label               = Onset Date
Did you add these spaces by accident?

2021-04-20 21:28 UTC, dkayiwa commented on api/src/main/resources/messages.properties
> +htmlformentry.error.handleTimezones                     = The attribute showTime=\"true\" requires time zone support to be enabled when client and server are on different time zones.
Are these spaces intentional?

2021-04-20 21:31 UTC, dkayiwa commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
> +
Are these the same as in UiFrameworkConstants.java?

2021-04-21 07:37 UTC, icrc-jfigueiredo commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
> +
Yes, because this project doesen't depent form UiFramework i cannot use that one.

2021-04-21 07:39 UTC, icrc-jfigueiredo commented on api/src/main/resources/messages.properties
> +htmlformentry.error.handleTimezones                     = The attribute showTime=\"true\" requires time zone support to be enabled when client and server are on different time zones.
Should be some auto-formatting, already remove them.

2021-04-21 20:47 UTC, dkayiwa commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
> +
Shouldn't the name be the same?

2021-04-22 19:33 UTC, merged