HTML-419:EncounterProviderAndRole and encounterProvider tags should display retired providers at the bottom,also add includeRetired
openmrs/openmrs-module-htmlformentry pull request #235
Opened 2021-03-29 12:33 UTC by HerbertYiga

Ticket ID

Description

encounterProviderAndRole and encounterProvider tags should display retired providers at the bottom,also add includeRetired Attribute (STILL IN PROGRESS)

2021-04-14 23:33 UTC, HerbertYiga commented
hi @mks-d  @ibacher  @mogoodrich  ,how do things look on this pr, i have included four screen shots after testing the encounterProviderAndRole  tag,will be glad to get your feed back

2021-04-16 19:32 UTC, mogoodrich requested changes
Thanks so much @HerbertYiga !

I made some suggestions for changes, let me know what you think!

2021-04-16 19:32 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +		includeRetired = TagUtil.parseParameter(parameters, "includeRetired", Boolean.class, true);
I know the original specifications said this should default to true, it looks like in the current behavior, retired providers are excluded by default, so let's default this property to false.

2021-04-16 19:32 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	public static List<Provider> getRetiredAndNonRetiredProviders(List<String> providerRoleIds,
This seems like a lot of duplicate code from the existing getProviders method.

Instead of creating this new method, could we:

* change the existing List<Provider> getAllProviders() method on line 2444 to "List<Provider> getAllProviders(boolean includeRetired)

* change the getProviders method above (line 2426) to take in a third parameter, "includeRetired"

* for backwards compatibility, create a getProviders(List<String> providerRolesId, boolean returnAllIfNoRolesSpecified) that just calls the new method we created above with includeRetired=false?

And while we are at it, add or modify any existing unit tests to test this.

Then see my comment below of how we would use this...

2021-04-16 19:32 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (!includeRetired) {
If we made the changes I suggested above, I think we could replace this whole block with:
providers = HtmlFormEntryUtil.getProviders(providerRoles, true, includeRetire)

2021-04-16 19:32 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +			if (provider.getRetired()) {
Would be nice to have a screenshot of how this looks.

2021-04-20 10:14 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +			if (provider.getRetired()) {
> Would be nice to have a screenshot of how this looks.

thanks  @mogoodrich  i have screen shots here https://issues.openmrs.org/browse/HTML-419

2021-04-20 10:15 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
> +	public static List<Provider> getRetiredAndNonRetiredProviders(List<String> providerRoleIds,
@mogoodrich  let me go on to make the recommended changes

2021-04-20 15:24 UTC, HerbertYiga commented
hi @mogoodrich how do things look now, i added the suggested changes, the screen shots exist on the ticket Id

2021-04-20 23:14 UTC, mogoodrich requested changes
Thanks @HerbertYiga !  Made a few more comments, let me know if that's clearer!

2021-04-20 23:14 UTC, mogoodrich commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/element/ProviderRoleAndElementTest.java
>  		// there are 4 providers in the provider roles dataset and one in the standard test dataset
nit pick, can we update this comment to explain why there are now 6?

2021-04-20 23:14 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
>  		if (providerRoleIds == null || providerRoleIds.isEmpty()) {
Can't this whole method now just call getProviders(providerRoleIds, returnAllIfNoRolesSpecified, false)

2021-04-20 23:14 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
and then this whole block could just be providers = HtmlFormEntryUtil.getProviders(providerRoles, true, includeRetired)

2021-04-21 07:49 UTC, HerbertYiga commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/element/ProviderRoleAndElementTest.java
>  		// there are 4 providers in the provider roles dataset and one in the standard test dataset
Fixed this

2021-04-21 07:49 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
>  		if (providerRoleIds == null || providerRoleIds.isEmpty()) {
Fixed this too

2021-04-21 07:50 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
> and then this whole block could just be providers = HtmlFormEntryUtil.getProviders(providerRoles, true, includeRetired)

Removing this block  only providers that are not retired are returned on testing

2021-04-21 08:07 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
@mogoodrich  No very sure why checks here fail with out any logs, but things pass well on building locally

2021-04-26 05:33 UTC, HerbertYiga commented
Hi @mogoodrich ,just a gentle reminder that i added some comments on this pr as seen above

2021-04-26 21:56 UTC, mogoodrich approved these changes
LGTM, thanks @HerbertYiga !

2021-04-27 08:20 UTC, mks-d requested changes

2021-04-27 08:20 UTC, mks-d commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java
> +	}
@HerbertYiga just asserting an array's size is not good enough.

Check that when you request non-retired ones there is indeed only non-retired ones. Then check that the diff between the array of all and the array of non-retired ones contains only retired ones.

Alternatively, if the dataset is small, just assert that you find in each array the provider ids that you are supposed to find.

2021-04-27 08:20 UTC, mks-d commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
@HerbertYiga I don't understand why @mogoodrich's suggestion couldn't be implemented?

2021-04-27 09:15 UTC, HerbertYiga commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java
> +	}
thanks @mks-d   let me do this

2021-04-27 13:24 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
Yeah, I was wondering if I was missing something...

2021-04-28 13:26 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java
> +			if (includeRetired) {
@mks-d  @mogoodrich  let me re check things here

2021-05-04 10:06 UTC, HerbertYiga commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java
> +		for(Provider provider:providers) {
hi  @mogoodrich  @mks-d   how do things look now for this  pr, fixed a couple of things as requested by @mks-d  thanks

2021-05-06 20:14 UTC, mogoodrich reviewed
Sorry @HerbertYiga  added one more comment, something I missed before...

2021-05-06 20:14 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Comparator<Provider> comparator = new Comparator<Provider>() {
It makes sense to sort retired Providers to the bottom, but we still want to sort by name after that....  was this new since the last PR?  Sorry if I missed it before.

2021-05-06 21:03 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Comparator<Provider> comparator = new Comparator<Provider>() {
Thanks @mogoodrich  this has been existing

2021-05-06 21:06 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Comparator<Provider> comparator = new Comparator<Provider>() {
> but we still want to sort by name after that

Does this mean we sort the retired providers by name after putting them at the bottom and we also sort the non retired providers by name

2021-05-07 00:29 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Comparator<Provider> comparator = new Comparator<Provider>() {
Yes... I'm trying to think if there's an easy way to do it just by using one comparator followed by another, but probably not...

2021-05-07 08:49 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Comparator<Provider> comparator = new Comparator<Provider>() {
> I'm trying to think if there's an easy way to do it just by using one comparator followed by another,

Thanks @mogoodrich  am also trying out to see how we can easly do this

2021-05-30 11:36 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
> +		Collections.sort(nonRetiredProviders, new ProviderByPersonNameComparator());
hi @mogoodrich,how do things look now we now ,we sort retired providers to the bottom and we still sort by name!

i have added the current screenshots to the ticket id

2021-05-30 13:50 UTC, HerbertYiga commented
@mogoodrich @dkayiwa   on using mvn clean install locally, every test passes well not sure some checks fail here

2021-06-02 19:14 UTC, mogoodrich commented
This looks good to me @HerbertYiga ... @mks-d are you okay with this?

The failing tests look like a known, unrelated issue: 
https://talk.openmrs.org/t/github-actions-builds-failing-on-ref-app-and-hfe-modules-and-probably-more-projects/33639/8

fyi, I will away on vacation starting tomorrow for 2 weeks, so you may need to remind me to merge when I get back... :)

2021-06-02 19:28 UTC, HerbertYiga commented
> fyi, I will away on vacation starting tomorrow for 2 weeks, so you may need to remind me to merge when I get back... :)

thanks much @mogoodrich  thought we could have this added in the next release of htmlformentry which is likely to be before two weeks since we are working on the reff app 2.12 that will be out at the end of this month, but still no objections of having things merged when you get back!!

2021-06-02 19:43 UTC, mogoodrich commented
@mks-d if you are okay with it I'm fine with you merging it in... just ping @mseaton so he can check for any ramifications in the PIH EMR after merging.

2021-06-16 17:09 UTC, mogoodrich commented
Alright, I'm back, going to merge this in!

2021-06-16 17:09 UTC, merged