HTML-788: Fix failing tests and refactor from 2.3 -> 2.4
openmrs/openmrs-module-htmlformentry pull request #265
Opened 2022-03-15 18:49 UTC by ibacher

## Description of what I changed

This fixes the tests broken by 8191e17, moves the code to depend on OpenMRS 2.4, which is the first to actually support the `FormRecordable` interface.

## Issue I worked on

see https://issues.openmrs.org/browse/HTML-788

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2022-03-15 21:31 UTC, mogoodrich requested changes
A small typo, but otherwise LGTM @ibacher !

2022-03-15 21:31 UTC, mogoodrich commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/EncounterProviderAndRoleTagTest.java
> +		executeVersionedDataSet("org/openmres/module/htmlformentry/data/encounterProviderAndRole.xml");
Typo?

2022-03-15 21:31 UTC, mogoodrich commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/EncounterProviderAndRoleTagTest.java
> +		executeVersionedDataSet("org/openmres/module/htmlformentry/data/encounterProviderAndRole.xml");
Typo?

2022-03-15 21:31 UTC, mogoodrich commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/MetadataSharingExportTest.java
> +		executeVersionedDataSet("org/openmres/module/htmlformentry/data/encounterProviderAndRole.xml");
Typo?

2022-03-15 21:31 UTC, mogoodrich commented on api-tests/src/test/java/org/openmrs/module/htmlformentry/MetadataSharingExportTest.java
> +		executeVersionedDataSet("org/openmres/module/htmlformentry/data/encounterProviderAndRole.xml");
Typo?

2022-03-16 13:38 UTC, ibacher commented
Thanks @mogoodrich! Yeah, that was a silly mistake.

2022-03-16 13:44 UTC, merged